# C: Line is too long.
LineLength:
  Enabled: false

# C: Missing top-level class documentation comment.
Documentation:
  Enabled: false

# C: Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

# C: Rename <from> to <to>.
PredicateName:
  Exclude:
    - lib/comable/columns_mapper.rb

# W: The use of eval is a serious security risk.
Eval:
  Exclude:
    - '**/Gemfile'

# C: Use the new Ruby 1.9 hash syntax.
HashSyntax:
  Exclude:
    - tasks/*

# C: Method has too many lines.
MethodLength:
  Exclude:
    - '**/db/migrate/*'

# Ignore files.
AllCops:
  Exclude:
    - vendor/**/*
    - lib/generators/comable/install/templates/**/*
    - spec/dummy/db/schema.rb
