# C: Line is too long.
LineLength:
  Enabled: false

# C: Missing top-level class documentation comment.
Documentation:
  Enabled: false

# C: Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

# W: The use of eval is a serious security risk.
Eval:
  Exclude:
    - '**/Gemfile'

# C: Use the new Ruby 1.9 hash syntax.
HashSyntax:
  Exclude:
    - tasks/*

# C: Method has too many lines.
MethodLength:
  Exclude:
    - '**/db/migrate/*'

# C: Assignment Branch Condition size for change is too high.
AbcSize:
  Exclude:
    - '**/db/migrate/*'

# C: Replace class var @@_ with a class instance var.
ClassVars:
  Exclude:
    - core/lib/comable/core/configuration.rb

# Ignore files.
AllCops:
  Exclude:
    - vendor/**/*
    - spec/dummy/db/schema.rb

# TODO: Remove after refactoring.
ClassLength:
  Exclude:
    - core/app/models/comable/order.rb
    - core/app/models/comable/customer.rb
