language:
  - ruby
rvm:
  - 2.1.2
env:
  - RAILS_VERSION=
  - RAILS_VERSION=4.0.0
  - RAILS_VERSION=3.2.0
before_install:
  - sh -c '[ "$RAILS_VERSION" = "" ] || rm Gemfile.lock'
  - sh -c '[ "$RAILS_VERSION" = "3.2.0" ] && echo "gem \"strong_parameters\"" >> Gemfile && echo "gem \"everywhere\"" >> Gemfile || :'
before_script:
  - psql -U postgres -c 'CREATE ROLE dummy WITH LOGIN CREATEDB;'
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - bundle exec rake
  - bundle exec rubocop
